### ISSUE TITLE
An error happened while trying to display this block

### ISSUE THREAD

**Issue by Steph876** [ThemeFuse/Brizy#1383]
I am currently facing an issue where some of the blocks in my page display "An error happened while trying to display this block" error message. 

How do I fix this?

More than 50% of my page is not showing due to this issue

**Comment by yancyglenn** [comment]
I am having the same issue on my home page.  Looking for answer

**Comment by NataliaBB** [comment]
Hello @Steph876 @yancyglenn 
Natalia here!
Please update the Brizy plugin to the latest versions:
Free Version 1.0.81
PRO Version 0.0.27

Thanks!
Regards, Natalia

**Comment by Steph876** [comment]
Hey Natalia, 

Everything is up to date on my site.

It seems as though in my update of the brizy plugin, all my global sections and saved sections were deleted. I do not see any blocks / sections that i saved or set to global when i look in the saved or global section when adding a new block. 

This new update has completely messed up my clients website. 

How can we fix this? How do I ensure it does not happen again?

**Comment by MaxZiebell** [comment]
Beware that Brizy pro is still beta. Use it as an early adopter.

**Comment by Steph876** [comment]
I get that, However i would expect the Brizy team to test their tool before doing an update. As it is if I revert to a backup it will have an old version of brizy on it which causes issues, and if I retain the current updated version, i loose some previous work I have done. It is like there is no real solution to the issue. But i am still waiting to hear from the brizy team as to how we can overcome this.

**Comment by NataliaBB** [comment]
Hello @Steph876 

The "An error happened while trying to display this block" has been fixed in 0.0.19 PRO version. 
After this update, I did not have any reports about this problem. 
Regarding "all my global sections and saved sections were deleted" this is not possible. The editor itself cannot remove any block.  
In any case, I will really appreciate if you can report this problem in a zendesk ticket, one of our developers can check this problem and solve it.
The link https://support.brizy.io/hc/en-us

Thank you! 
Natalia

**Comment by NataliaBB** [comment]
@MaxZiebell  thanks for your messages.

**Comment by Steph876** [comment]
@NataliaBB I have opened an ticket and given the team my credentials, It has been over a week and I have not heard anything back from them.

**Comment by NataliaBB** [comment]
hi @Steph876 

Please, give me your ticket number I will check with the team.
Thanks a lot!

Natalia

**Comment by astroboy67** [comment]
IM getting the issue too, I uninstall and reintall Brizy latest version and still getting the error

**Comment by NataliaBB** [comment]
Hello @astroboy67 
If you still have this issue, please send a ticket to us with the wp credentials. 
Link: https://support.brizy.io/hc/en-us 
Thank you!

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
