### ISSUE TITLE
Text formatting font issue - Default Serif font is displayed

### ISSUE THREAD

**Issue by quantumleap33** [ThemeFuse/Brizy#538]
I have just realized that when editing a font and selecting a font from the left side of the typography panel, update then view the page, the font is not applied and it displays the default Serif one instead. You would first need to create a font style from the Styling section with the desired font, then select that while formatting the text to be able to save the font properly. That can be confusing for users since they will be expecting the custom font set while formatting the font to be displayed as it is previewed on the Brizy edit page.

**Comment by quantumleap33** [comment]
Just to add to this, JP, and reiterate, the issue occurs generally on text formatting not specifically text for dynamic content.

**Comment by rockalife** [comment]
Hi guys

 @quantumleap33 

The issue with the font family not being applied has been fixed and will be shipped in the next update. Thank you for letting us know.

@pellissierjp 

1. It is the same issue that @quantumleap33 reported. It has been fixed and will be shipped in the next update.
2. This looks like a totally separate problem and you can open a new issue if you want. We will look into that. Thank you for reporting

**Comment by quantumleap33** [comment]
@pellissierjp Hey JP, I just saw what you mean by that, it's defenitely a big one! Please raise a separate issue for this for sure! Even though I think the team could have easily reproduce that and solve this as well, it's pretty obvious!

**Comment by quantumleap33** [comment]
Issue (1) seems to have been resolved since latest Brizy 1.0.27 update. Issue (2) still present.

**Comment by pellissierjp** [comment]
Hi, Sergiu

Should we still log a separate issue for the post content not displaying in the font we set via dynamic content?
I checked with 0.0.4, this issue is still present, though for headings it's been fixed.

**Comment by Aarebern** [comment]
Hi all,

any updates or progress on this issue? With the latest builds I have absolutely no text styling applied for #Post Content.

Thanks,
Mark

**Comment by allardo** [comment]
Same problem here.. #Post_Content is not working with the right font, whatever I try..

**Comment by NataliaBB** [comment]
Hi! 

I’m closing this issue to keep the issue database slim. Feel free to re-open if I’ve misunderstood you.

Regards. Natalia
