### ISSUE TITLE
Brizy and Pods Integration Bugs and Documentation Pitfalls

### ISSUE THREAD

**Issue by willhousecreative** [ThemeFuse/Brizy#728]
I started in on the PODS integration with Brizy Pro using the guidelines here: [https://brizy.io/blog/brizy-pro-toolset-and-pods/]()

However, I found that none of the custom fields were available to me when I went to create the Brizy template. I edited a screencast of my workflow to help with any questions. Here are the highlights:

- Brizy admin menu disappears when editing a post in the "Cars" content type.
- Brizy instructions designate a category but categories are not enabled automatically when creating a PODS Post Type. I had to enable them. 
- None of the custom fields that I created in PODS were available to me when I went to create my Brizy template.

I am using Wordpress Version 4.9.8 on a MAMP localhost, MAC Powerbook. MySql version 5.6.35. PHP version 7.1.8

[![Brizy and Pods Integration Bugs Screencast](http://img.youtube.com/vi/wh1NwxLdYXQ/0.jpg)](http://www.youtube.com/watch?v=wh1NwxLdYXQ "Brizy and Pods Integration Bugs Screencast")

**Comment by 4Designs** [comment]
Got the same issue as you: "None of the custom fields that I created in PODS were available to me when I went to create my Brizy template."
Pods is pretty useless if I can't make archive pages/pages with multiple pods. Single Pods page works, nothing else I'm afraid. 

However, Brizy admin menu does not disappear for me.

**Comment by ViorelEremia** [comment]
@willhousecreative thank you for your great video.
We knit a big update this week with some modifications on dynamic content. 
About "Brizy admin menu disappears when editing a post" is fixed. 
About "Brizy instructions designate a category but categories ....." it's a mistake in that articles you are right need to enable in the pod's settings.
@4Designs next updates(free and pro) will fix the archives pages and users.
About no fields in brizy build mode can you guys try with the latest version of brizy free 1.0.39?

**Comment by willhousecreative** [comment]
@ViorelEremia 

I have updated Brizy to Version 1.0.39 on the localhost you saw in the video. 

At present, the Brizy menu item is still disappearing. I tried disabling the "Classic Editor" plugin but the issue still persists. I also created an entirely new Pod called Books. Again, same problem. Once the URL tries to fetch something like  "[mydomain]/post.php?post=[id]&action=edit" Brizy disappears. 

Also, I went back into my Brizy "Pods Template". There are still no custom fields available. 

I created a template with the condition to Include > Books > All and another to Include > Cars > All and still no custom fields. I also built a template to Include > Cars > Audi A4 D4, again, same result. 

Finally I trashed my original template (FYI, I got an error trying to use the same rule in two different templates: "The rule is already used in one template") and rebuilt the template with the original condition Include > Categories > Pod Cars and still no custom fields. 

I hope this helps in some way.

**Comment by ViorelEremia** [comment]
Sorry @willhousecreative about item menu I fixed it; the next update has it(1.0.39+).
With pro 1.0.10 and free 1.0.39 I followed all your steps and I have all custom fields available added by pods. Can you create a backup[ with all in one migration](https://wordpress.org/plugins/all-in-one-wp-migration/) and paste it here or you can send it to my email: ```viorel@themefuse.com```. 
About rules It is fixed here: https://github.com/ThemeFuse/Brizy/pull/772

**Comment by willhousecreative** [comment]
@ViorelEremia – I did have some success. 

Navigating to Brizy Role Manager > Setting the Activate Brizy For > and selecting the custom Pod allowed me to then choose fields in a single post template (see screen cast).

However, I was still unable to choose custom fields when creating archive templates. 

I duplicated the testing site to a subdomain for your team to log in and test. I will be sending log in details via Facebook messenger. 

[![Brizy/Pods Screencast](https://img.youtube.com/vi/4CR-hT2m46g/maxresdefault.jpg)](http://www.youtube.com/watch?v=4CR-hT2m46g "Brizy/Pods Screencast")
